const ADD_NEW_QUESTION = `question:ADD_NEW_QUESTION`;
const DELETE_QUESTION = `question:DELETE_QUESTION`;
const UPDATE_QUESTION = `question:UPDATE_QUESTION`;
const GET_ALL_QUESTIONS = `question:GET_ALL_QUESTION`;

module.exports = {
  ADD_NEW_QUESTION,
  DELETE_QUESTION,
  UPDATE_QUESTION,
  GET_ALL_QUESTIONS,
};
