const ADD_NEW_LEVEL = `level:ADD_NEW_LEVEL`;
const GET_ALL_LEVELS = `level:GET_ALL_LEVEL`;
const GET_LEVEL_INFO = `level:GET_LEVEL_INFO`;
const UPDATE_LEVEL = `level:UPDATE_LEVEL`;
const DELETE_LEVEL = `level:DELETE_LEVEL`;

module.exports = {
  ADD_NEW_LEVEL,
  GET_ALL_LEVELS,
  GET_LEVEL_INFO,
  UPDATE_LEVEL,
  DELETE_LEVEL,
};
