const ADD_SUBJECT = `subject:ADD_SUBJECT`;
const GET_SUBJECT_INFO = `subject:GET_SUBJECT_INFO`;
const DELETE_SUBJECT = `subject:DELETE_SUBJECT`;
const GET_ALL_SUBJECTS = `subject:GET_ALL_SUBJECTS`;
const UPDATE_SUBJECT = `subject:UPDATE_SUBJECT`;

module.exports = {
  ADD_SUBJECT,
  GET_ALL_SUBJECTS,
  GET_SUBJECT_INFO,
  DELETE_SUBJECT,
  UPDATE_SUBJECT,
};
