const ADD_DEPARTMENT = `department:ADD_DEPARTMENT`;
const UPDATE_DEPARTMENT = `department:UPDATE_DEPARTMENT`;
const GET_ALL_DEPARTMENTS = `department:GET_ALL_DEPARTMENTS`
const GET_DEPARTMENT_INFO = `department:GET_DEPARTMENT_INFO`;
const DELETE_DEPARTMENT = `department:DELETE_DEPARTMENT`;

module.exports ={
    ADD_DEPARTMENT,
    UPDATE_DEPARTMENT,
    GET_ALL_DEPARTMENTS,
    GET_DEPARTMENT_INFO,
    DELETE_DEPARTMENT
};